---
title: "Estudio del injerto intermedio sobre el crecimiento y productividad del mango (Mangífera indica L.) var.Kent.en el Valle de San Lorenzo"
author: Sebastian Casas; Flavio Lozano-Isla
format:
  html:
    toc: true
    toc-location: left
    number-sections: true
    self-contained: true
    output-file: "ESM_1"
editor_options: 
  chunk_output_type: console
execute: 
  warning: false
  echo: true
---

# Setup

```{r}
#| label:  setup

library(emmeans) 
library(multcomp)
source('https://inkaverse.com/setup.r')

session_info()
```

# Importar datos

```{r}
url <- "https://docs.google.com/spreadsheets/d/1E_cUmiRFoPLGAj7AQC6HZBD6hXtqzg2UHPvtWr2QR_U/edit#gid=2112492836"

gs <- url %>% 
  as_sheets_id()

ley <- gs %>% 
  range_read("leyenda") %>% 
  rename(tratamientos = TRATAM) %>% 
  rename_with(~ tolower(.))

rdt <- gs %>% 
  range_read("db") %>% 
  merge(., ley, ) %>% 
  select(year = "año", n, tratamientos,n_trat:yema, everything()) %>% 
  rename(treat = tratamientos
         , n_treat = n_trat
         , block = bloque
         , n_plant = n_planta
         , height = alt_planta
         , n_fruits = n_frutos
         , flowering = per_floracion
         , sproud = per_brote
         , scion = yema
         , stock = patron
         , edge = puente
         ) %>% 
  dplyr::arrange(year, n, treat) %>% 
  mutate(across(year:n_plant, ~ as.factor(.)))
  
fru <-  gs %>% 
  range_read("db_frutos")
```

# Data summary

```{r}
sm <- rdt %>% 
  group_by(year, treat) %>% 
  summarise(across(height:sproud, ~ sum(!is.na(.))))
```

# Objetivos

- Determinar las caracteristicas agronómicas por tipo de injerto intermedio para las variables alt_planta	n_frutos	per_floracion

- Evaluar la calidad del fruto por tipo de injerto intermedio

# Plant height

```{r}
model <- rdt %>% 
  lm(height  ~ block + treat, .)

plot_diag(model) %>% 
  plot_grid(plotlist = ., ncol = 2)

rdt %>% 
  plot_raw(x = "treat", y = "height")

anova(model)

# mc <- emmeans(model, ~ treat) %>% 
#   cld(Letters = letters, reversed = T) %>% 
#   mutate(across(.group, trimws))

mc <- agricolae::duncan.test(model, trt = c("treat")) %>% 
  pluck("groups") %>% 
  rownames_to_column("treat")

mc %>% 
  plot_smr(x = "treat"
           , y = "height"
           , sig = "groups"
           , ylimits = c(0, 6, 1)
           )
```

# Plant sproud

```{r}
model <- rdt %>% 
  lm(sproud  ~ block + treat, .)

plot_diag(model) %>% 
  plot_grid(plotlist = ., ncol = 2)

rdt %>% 
  plot_raw(x = "treat", y = "sproud")

anova(model)

# mc_2 <- emmeans(model, ~ treat) %>% 
#   cld(Letters = letters, reversed = T) %>% 
#   mutate(across(.group, trimws))

mc <- agricolae::duncan.test(model, trt = c("treat")) %>% 
  pluck("groups") %>% 
  rownames_to_column("treat")

mc %>% 
  plot_smr(x = "treat"
           , y = "sproud"
           , sig = "groups"
           , ylimits = c(0, 80, 10)
           )
```

# Number of fruits

```{r}
model <- rdt %>% 
  lm(n_fruits  ~ block + treat + year + treat:year, .)

plot_diag(model) %>% 
  plot_grid(plotlist = ., ncol = 2)

rdt %>% 
  plot_raw(x = "treat", y = "n_fruits", group = "year")

anova(model)

mc <- agricolae::duncan.test(model, trt = c("treat", "year")) %>% 
  pluck("groups") %>% 
  rownames_to_column("treat") %>% 
  separate(treat, c("treat", "year"))

mc %>% 
  plot_smr(x = "treat"
           , y = "n_fruits"
           , group = "year"
           , sig = "groups"
           , ylimits = c(0, 250, 50)
           )


```

# Flowering

```{r}
model <- rdt %>% 
  lm(flowering  ~ block + treat + year + treat:year, .)

plot_diag(model) %>% 
  plot_grid(plotlist = ., ncol = 2)

rdt %>% 
  plot_raw(x = "treat", y = "flowering", group = "year")

anova(model)

mc <- agricolae::duncan.test(model, trt = c("treat", "year")) %>% 
  pluck("groups") %>% 
  rownames_to_column("treat") %>% 
  separate(treat, c("treat", "year"))

mc %>% 
  plot_smr(x = "treat"
           , y = "flowering"
           , group = "year"
           , sig = "groups"
           , ylimits = c(0, 100, 20)
           )

```

















